MotoGP/Models/ErrorViewModel.cs
using System;

namespace MotoGP.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MotoGP/Models/Race.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MotoGP.Models
{
    public class Race
    {
        public int RaceID { get; set; }
        public string Name { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    }
}

MotoGP/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MotoGP.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MotoGP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Menu()
        {
            Random random = new Random();
            string banner = $"banner{random.Next(1, 5)}.jpg";
            ViewData["Banner"] = banner;
            return View();
        }
    }
}

MotoGP/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MotoGP.Models;

namespace MotoGP.Controllers
{
    public class InfoController : Controller
    {
        public IActionResult ListRaces()
        {
            int banner = 1;
            ViewData["Banner"] = banner;
            return View();
        }

        public IActionResult ListTeams()
        {
            int banner = 2;
            ViewData["Banner"] = banner;
            return View();
        }

        public IActionResult ListRiders()
        {
            int banner = 3;
            ViewData["Banner"] = banner;
            return View();
        }

        public IActionResult BuildMap()
        {
            List<Race> races = new List<Race>();
            races.Add(new Race() { RaceID = 1, X = 517, Y = 19, Name = "Assen" });
            races.Add(new Race() { RaceID = 2, X = 859, Y = 249, Name = "Losail Circuit" });
            races.Add(new Race() { RaceID = 3, X = 194, Y = 428, Name = "Autódromo Termas de Río Hondo" });

            ViewData["Banner"] = 1;
            return View(races);
        }
    }
}

MotoGP/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MotoGP.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult OrderTicket()
        {
            ViewData["Banner"] = 4;
            return View();
        }

        public IActionResult ConfirmOrder()
        {
            DateTime dateTime = DateTime.Today;
            ViewData["Banner"] = 4;
            ViewData["Message"] = $"Thank you for ordering tickets! Your booking is registered on {dateTime.ToString("dd/MM/yyyy")}. We will send out your tickets in the coming week.";
            return View();
        }
    }
}

MotoGP/Views/Home/Index.cshtml
@{ 
    Layout = "~/Views/Shared/_NewLayout.cshtml";

    ViewData ["Title"] = "Home Page";
}

<style>
    .centered{
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%)
    }
</style>

<div>
    <a asp-controller="Home" asp-action="Menu">
        <img src="~/images/allerlei/logo.png" class="centered" />
    </a>
</div>

MotoGP/Views/Home/Menu.cshtml
@{
    Layout = "~/Views/Shared/_NewLayout.cshtml";

    ViewData["Title"] = "Menu";
}

<style>
    .centered {
        margin: 0;
        position: absolute;
        top: 50%;
        left: 50%;
        margin-right: -50%;
        transform: translate(-50%, -50%)
    }

    .totalPage {
        width: 100%;
        margin: 5px;
        z-index: 0;
    }
</style>
@{ 
    var src = ViewData["Banner"];
}
<div>
    <img src="~/images/allerlei/@src" class="totalPage"/>
</div>
<div class="centered">
    <div class="d-flex justify-content-center">
        <a asp-controller="Info" asp-action="ListRaces">
            <img src="~/images/allerlei/races.png" />
        </a>
        <a asp-controller="Info" asp-action="ListTeams">
            <img src="~/images/allerlei/teams.png" />
        </a>
    </div>
    <div>
        <a asp-controller="Info" asp-action="ListRiders">
            <img src="~/images/allerlei/riders.png" />
        </a>
        <a asp-controller="Shop" asp-action="OrderTicket">
            <img src="~/images/allerlei/tickets.png" />
        </a>
    </div>
</div>

MotoGP/Views/Info/BuildMap.cshtml
@model List<MotoGP.Models.Race>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewData["Title"] = "Races on Map";
}
<div>
    <img src="~/images/allerlei/map.png" alt="Map" usemap="#map" />
    <map name="map">
        @{
            foreach (var race in Model)
            {
                <area shape="circle" coords="@race.X, @race.Y, 10" alt="@race.Name" href="@Url.Action("ShowRace", "Info", new { id = race.RaceID})" />
            }
        }

    </map>
</div>
<br />
<div>
    <a asp-controller="Info" asp-action="ListRaces">Back</a>
</div>

MotoGP/Views/Info/ListRaces.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewData["Title"] = "List of races";
}

<a asp-controller="Home" asp-action="Menu">Back</a> | <a asp-controller="Info" asp-action="BuildMap">Races on map</a> | <a asp-controller="Info" asp-action="SelectRace">One by one</a>

MotoGP/Views/Info/ListRiders.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewData["Title"] = "List of riders";
}

<a asp-controller="Home" asp-action="Menu">Back</a>

MotoGP/Views/Info/ListTeams.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewData["Title"] = "Team List";
}

<a asp-controller="Home" asp-action="Menu">Back</a>

MotoGP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<style>
    h1 {
        color: crimson;
    }

    .totalPage {
        width: 100%;
        margin: 5px;
        z-index: 0;
    }
</style>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title> @ViewData["Title"] - MotoGP</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

@{
    var banners = new List<string>
    {
        "bannerRaces.jpg", "bannerRiders.jpg", "bannerTeams.jpg", "bannerTickets.jpg"
    };
}
<body>
    @{
        var src = "";
        switch (ViewData["Banner"])
        {
            case 1:
                src = banners[0];
                break;

            case 2:
                src = banners[2];
                break;

            case 3:
                src = banners[1];
                break;

            case 4:
                src = banners[3];
                break;
        }
    }
    <div>
        <a asp-controller="Home" asp-action="Index">
            <img src="~/images/allerlei/@src" class="totalPage" />
        </a>
    </div>

    <div>
        <h1>@ViewData["Title"]</h1>
    </div>
    <p>@ViewData["Message"]</p>
    <div>
        @RenderBody()
    </div>
</body>
</html>

MotoGP/Views/Shared/_NewLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title> @ViewData["Title"] - MotoGP</title>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>

<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

MotoGP/Views/Shop/ConfirmOrder.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewData["Title"] = "Confirmation";
}

<a asp-controller="Home" asp-action="Menu">Back</a>

MotoGP/Views/Shop/OrderTicket.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewData["Title"] = "Order tickets";
}

<a asp-controller="Home" asp-action="Menu">Back</a>